sources:
  - name: Hashnode
    handler:
      graphql:
        endpoint: https://gql.hashnode.com
    transforms:
      - prefix:
          mode: wrap
          value: hn_
          includeRootOperations: true
          includeTypes: true
      - encapsulate:
          applyTo:
            query: true
            mutation: true
            subscription: true

  - name: Github
    handler:
      graphql:
        endpoint: https://api.github.com/graphql
        source: https://docs.github.com/public/schema.docs.graphql
        operationHeaders:
          Authorization: bearer {env.NEXT_PUBLIC_GITHUB_TOKEN}
          User-Agent: GraphQL
    transforms:
      - prefix:
          mode: wrap
          value: gh_
          includeRootOperations: true
          includeTypes: true
      - encapsulate:
          applyTo:
            query: true
            mutation: true
            subscription: true

documents:
  - ./src/**/*.graphql
